language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script: true
after_success:
- docker run -p 8088:80 -d --name htmltest $DOCKER_USERNAME/htmltest:latest
service: docker
